/*
================================================================================
FILE: 10_Sales_Analysis_Project.sql
PROJECT: Sales Performance Analysis
DATASET: Parch & Posey
AUTHOR: Mohd Hussain
================================================================================

PROJECT DESCRIPTION:
This project analyzes sales performance, customer revenue contribution,
and purchasing behavior using the Parch & Posey dataset.

The objective is to identify key revenue drivers, evaluate sales
performance, and understand customer activity using SQL-based analysis.

TABLES USED:
accounts
orders
sales_reps
region
web_events

KEY METRICS ANALYZED:
• Customer Revenue Contribution
• Regional Sales Performance
• Sales Representative Performance
• Revenue Trends Over Time
• Customer Purchasing Behavior
• Product Demand
• Marketing Channel Effectiveness

TOOLS USED:
PostgreSQL
SQL (Joins, Aggregations, Window Functions, Subqueries)

================================================================================
*/

/*
--------------------------------------------------------------------------------
QUERY 1 — Top Revenue Generating Customers
--------------------------------------------------------------------------------
*/

/*QUESTION:
Which customer accounts contribute the most to total company revenue? Identify the highest revenue-generating customers.

REWRITE:
Calculate the total revenue generated by each customer account by joining the accounts and orders tables.
Aggregate total_amt_usd for each account and sort customers from highest to lowest revenue contribution to identify
the top revenue-generating customers.

LOGIC:
1. Join the accounts table with the orders table using account_id.
2. Aggregate total_amt_usd to calculate total revenue for each account.
3. Group the results by account name.
4. Sort customers in descending order of revenue to identify top contributors.*/

SELECT a.name AS account_name,
       SUM(o.total_amt_usd) AS total_revenue
FROM accounts a
JOIN orders o
ON a.id = o.account_id
GROUP BY a.name
ORDER BY total_revenue DESC
LIMIT 10;

/*INSIGHT:
The analysis shows that a small number of customer accounts contributes a significant portion of total company revenue.
This indicates strong revenue concentration among high-value customers.

Retaining these accounts is critical for revenue stability, and the sales team should prioritize relationship management
and long-term engagement with these key clients.*/