/*
================================================================================
FILE: 10_Sales_Analysis_Project.sql
PROJECT: Sales Performance Analysis
DATASET: Parch & Posey
AUTHOR: Mohd Hussain
================================================================================

PROJECT DESCRIPTION:
This project analyzes sales performance, customer revenue contribution,
and purchasing behavior using the Parch & Posey dataset.

The objective is to identify key revenue drivers, evaluate sales
performance, and understand customer activity using SQL-based analysis.

TABLES USED:
accounts
orders
sales_reps
region
web_events

KEY METRICS ANALYZED:
• Customer Revenue Contribution
• Regional Sales Performance
• Sales Representative Performance
• Revenue Trends Over Time
• Customer Purchasing Behavior
• Product Demand
• Marketing Channel Effectiveness

TOOLS USED:
PostgreSQL
SQL (Joins, Aggregations, Window Functions, Subqueries)

================================================================================
*/

/*
--------------------------------------------------------------------------------
QUERY 1 — Top Revenue Generating Customers
--------------------------------------------------------------------------------
*/

/*QUESTION:
Which customer accounts contribute the most to total company revenue? Identify the highest revenue-generating customers.

REWRITE:
Calculate the total revenue generated by each customer account by joining the accounts and orders tables.
Aggregate total_amt_usd for each account and sort customers from highest to lowest revenue contribution to identify
the top revenue-generating customers.

LOGIC:
1. Join the accounts table with the orders table using account_id.
2. Aggregate total_amt_usd to calculate total revenue for each account.
3. Group the results by account name.
4. Sort customers in descending order of revenue to identify top contributors.*/

SELECT a.name AS account_name,
       SUM(o.total_amt_usd) AS total_revenue
FROM accounts a
JOIN orders o
ON a.id = o.account_id
GROUP BY a.name
ORDER BY total_revenue DESC
LIMIT 10;

/*INSIGHT:
The analysis shows that a small number of customer accounts contributes a significant portion of total company revenue.
This indicates strong revenue concentration among high-value customers.

Retaining these accounts is critical for revenue stability, and the sales team should prioritize relationship management
and long-term engagement with these key clients.*/


/*
--------------------------------------------------------------------------------
QUERY 2 — Regional Revenue Performance
--------------------------------------------------------------------------------
*/

/*QUESTION:
Which geographic regions generate the highest revenue for the company?
Analyze total revenue contribution by region to identify the strongest performing markets.

REWRITE:
Calculate the total revenue generated in each region by joining the orders, accounts, sales_reps, and region tables.
Aggregate total_amt_usd for each region and sort the results from highest to lowest revenue contribution.

LOGIC:
1. Join orders with accounts using account_id.
2. Join accounts with sales_reps using sales_rep_id.
3. Join sales_reps with region using region_id.
4. Aggregate total_amt_usd to compute total revenue generated in each region.
5. Group results by region name.
6. Sort regions in descending order of revenue.*/

SELECT r.name AS region_name,
       SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a
ON o.account_id = a.id
JOIN sales_reps sr
ON sr.id = a.sales_rep_id
JOIN region r
ON r.id = sr.region_id
GROUP BY r.name
ORDER BY total_revenue DESC;

/*INSIGHT:
This analysis reveals which geographic regions contribute the largest share of company revenue.

Regions generating higher revenue likely have stronger customer relationships, more active sales representatives,
or greater product demand.

Understanding regional performance helps leadership allocate sales resources effectively and identify markets with strong growth potential.
*/



/*
--------------------------------------------------------------------------------
QUERY 3 — Sales Representative Performance
--------------------------------------------------------------------------------
*/

/*QUESTION:
Which sales representatives generate the highest revenue for the company?
Evaluate total revenue contribution by each sales rep and identify top-performing representatives.

REWRITE:
Calculate total revenue generated by each sales representative by joining orders, accounts, and sales_reps tables.
Aggregate total_amt_usd for each sales rep and sort them from highest to lowest revenue contribution to identify top performers.

LOGIC:
1. Join orders with accounts using account_id.
2. Join accounts with sales_reps using sales_rep_id.
3. Aggregate total_amt_usd to compute total revenue for each sales rep.
4. Group results by sales rep name.
5. Sort sales reps in descending order of revenue.
6. Limit results to highlight top-performing sales reps.
*/

SELECT sr.name AS sales_rep_name,
       SUM(o.total_amt_usd) AS total_revenue
FROM orders o
JOIN accounts a
ON o.account_id = a.id
JOIN sales_reps sr
ON a.sales_rep_id = sr.id
GROUP BY sr.name
ORDER BY total_revenue DESC
LIMIT 10;

/*INSIGHT:
The analysis highlights the top-performing sales representatives based on total revenue generated.

A small group of sales reps contributes a significant portion of overall revenue, indicating performance concentration within the sales team.

Identifying top performers helps in understanding effective sales strategies,
while lower-performing reps may require support, training, or reassignment to improve overall team performance.
*/



/*
--------------------------------------------------------------------------------
QUERY 4 — Revenue Trend and Year-over-Year Growth Analysis
--------------------------------------------------------------------------------
*/

/*QUESTION:
How has the company's revenue changed year over year, and which periods show significant growth or decline?
Evaluate annual revenue performance and calculate year-over-year (YoY) growth to support business performance monitoring and
strategic planning.

REWRITE:
Calculate total revenue for each year using the orders table.
Then compare each year's revenue with the previous year by using a window function to retrieve prior values.
Compute both the absolute revenue change and the percentage growth to identify performance trends over time.

LOGIC:
1. Use the orders table to access revenue and transaction timestamps.
2. Extract the year from occurred_at using DATE_TRUNC.
3. Aggregate total_amt_usd to compute total revenue per year.
4. Use LAG() to obtain the previous year's revenue.
5. Calculate:
              revenue change = current year - previous year
              growth percentage = (change / previous year) * 100
6. Use NULLIF to prevent division by zero errors.
7. Sort results chronologically for proper trend analysis.
*/

WITH yearly_revenue AS (SELECT DATE_TRUNC('year', occurred_at) AS year,
                               SUM(total_amt_usd) AS total_revenue
                        FROM orders
                        GROUP BY year),

     revenue_with_lag AS (SELECT year,
                                 total_revenue,
                                 LAG(total_revenue) OVER (ORDER BY year) AS previous_year_revenue
                          FROM yearly_revenue)

SELECT year,
       total_revenue,
       previous_year_revenue,
       total_revenue - previous_year_revenue AS revenue_change,
       (total_revenue - previous_year_revenue) * 100.0
       / NULLIF(previous_year_revenue, 0) AS yoy_growth_percentage
FROM revenue_with_lag
ORDER BY year;

/*INSIGHT:
Revenue shows strong growth from 2013 to 2016, with particularly significant increases between 2013-2014 and 2015-2016,
indicating periods of rapid business expansion.

However, 2017 shows a sharp decline in revenue and a significant negative growth rate.
This is likely due to incomplete or partial-year data rather than an actual business drop.

The unusually high growth (978%) between 2013-2014 is driven by a low base year,
which exaggerates percentage growth and should be interpreted with caution.

This analysis highlights both growth momentum and potential data limitations,
emphasizing the importance of validating time-based datasets before drawing conclusions.
*/