/*
================================================================================
FILE: 10_Sales_Analysis_Project.sql
PROJECT: Sales Performance Analysis
DATASET: Parch & Posey
AUTHOR: Mohd Hussain
================================================================================

PROJECT DESCRIPTION:
This project analyzes sales performance, customer revenue contribution,
and purchasing behavior using the Parch & Posey dataset.

The objective is to identify key revenue drivers, evaluate sales
performance, and understand customer activity using SQL-based analysis.

TABLES USED:
accounts
orders
sales_reps
region
web_events

KEY METRICS ANALYZED:
• Customer Revenue Contribution
• Regional Sales Performance
• Sales Representative Performance
• Revenue Trends Over Time
• Customer Purchasing Behavior
• Product Demand
• Marketing Channel Effectiveness

TOOLS USED:
PostgreSQL
SQL (Joins, Aggregations, Window Functions, Subqueries)

================================================================================
*/

/*
--------------------------------------------------------------------------------
QUERY 1 — Top Revenue Generating Customers
--------------------------------------------------------------------------------
*/

/*QUESTION:
Which customer accounts contribute the most to total company revenue? Identify the highest revenu-generating customers.

REWRITE:
Calculate the total revenue generated by each customer account using the orders table and sort customers from highest to lowest
based on their revenue contribution.

LOGIC:
1. Join the accounts table with the orders table using account_id.
2. Aggregate total_amt_usd for each customer account.
3. Group results by account name.
4. Sort the results in descending order of total revenue.*/

SELECT a.name AS account_name,
       SUM(o.total_amt_usd) AS total_revenue
FROM accounts a
JOIN orders o
ON a.id = o.account_id
GROUP BY a.name
ORDER BY total_revenue DESC
LIMIT 10;

/*INSIGHT:
The analysis shows that a small group of customer accounts contributes a large share of total company revenue.
This indicates a concentration of revenue among high-value customers.

Maintaining strong relationships with these key accounts is critical for revenue stability,
and the sales team should prioritize retention and long-term engagement strategies with these customers.*/