/*
FILE: 02_Aggregations.sql

DESCRIPTION:
This file demonstrates how aggregate functions are used to summarize data
and generate analytical metrics from transactional datasets.

KEY CONCEPTS:
- Aggregate functions (SUM, COUNT, AVG, MIN, MAX)
- GROUP BY for grouping records
- HAVING for filtering aggregated results
- Creating summary metrics for analysis
*/


/*QUESTION:
How many orders were placed in total?

REWRITE:
1) Final Output: One number - total count of orders.
2) Group/Scope: No grouping required
3) Selection Logic: Include all rows from the orders table.
4) Final Calculation: Count total number of rows.

LOGIC: First consider all orders. Then count the total number of orders.*/

SELECT COUNT(*) AS total_orders
FROM orders;


/*QUESTION:
How many orders have a NULL value in standard_qty?

REWRITE:
1) Final Output: One number - count of orders with NULL standard_qty.
2) Group/Scope: No grouping required.
3) Selection Logic: Keep only rows where standard_qty is NULL.
4) Final Calculation: Count total rows.

LOGIC: Filter orders where standard_qty is NULL. Count the remaining rows.*/

SELECT COUNT(*) AS total_null
FROM orders
WHERE standard_qty IS NULL;


/*QUESTION:
What is the total revenue (total_amt_usd) generated from all orders?

REWRITE:
1) Final Output: One number - total revenue from all orders.
2) Group/Scope: No grouping required.
3) Selection Logic: Include all rows from the orders table.
4) Final Calculation: SUM(total_amt_usd).

LOGIC: First consider all orders. Then SUM(total_amt_usd) to calculate total revenue.*/

SELECT SUM(total_amt_usd) AS total_revenue
FROM orders;


/*QUESTION:
What is the total revenue generated by each account?

REWRITE:
1) Final Output: Multiple rows - total revenue for each account.
2) Group/Scope: Group by account_id to find total revenue per account.
3) Selection Logic: Include all orders.
4) Final Calculation: SUM(total_amt_usd) per account.

LOGIC: Group orders by account_id. SUM(total_amt_usd) for each group.*/

SELECT account_id,
       SUM(total_amt_usd) AS total_revenue_per_acc
FROM orders
GROUP BY account_id;


/*QUESTION:
What is the smallest and largest order value (total_amt_usd) in the dataset?

REWRITE:
1) Final Output: One row - smallest and largest order values.
2) Group/Scope: No grouping required.
3) Selection Logic: Include all orders.
4) Final Calculation: MIN and MAX of total_amt_usd.

LOGIC: Consider all orders. Calculate the minimum and maximum total_amt_usd values.*/

SELECT MIN(total_amt_usd) AS smallest_order,
       MAX(total_amt_usd) AS largest_order
FROM orders;


/*QUESTION:
What is the highest total revenue generated by any single account?

REWRITE:
1) Final Output: One row - account_id and highest total revenue.
2) Group/Scope: Group by account_id.
3) Selection Logic: Include all orders.
4) Final Calculation: SUM of total_amt_usd per account and select the highest value.

LOGIC: Group orders by account_id. SUM total_amt_usd for each account. Sort totals in descending order and return the top result.*/

SELECT account_id,
       SUM(total_amt_usd) AS highest_revenue
FROM orders
GROUP BY account_id
ORDER BY highest_revenue DESC
LIMIT 1;


/*QUESTION:
What is the average order value (total_amt_usd) across all orders?

REWRITE:
1) Final Output: One number - average order value.
2) Group/Scope: No grouping required.
3) Selection Logic: Include all orders.
4) Final Calculation: AVG of total_amt_usd across all orders.

LOGIC: Consider all orders. Then AVG(total_amt_usd) to calculate average order value.*/

SELECT AVG(total_amt_usd) AS avg_order_value
FROM orders;


/*QUESTION:
What is the average order value per account?

REWRITE:
1) Final Output: Multiple rows - account_id and average order value.
2) Group/Scope: Group by account_id.
3) Selection Logic: Include all orders.
4) Final Calculation: AVG of total_amt_usd per account.

LOGIC: Group orders by account_id. Then AVG(total_amt_usd) to calculate avg value for each account.*/

SELECT account_id,
       AVG(total_amt_usd) avg_per_acc
FROM orders
GROUP BY account_id;


/*QUESTION:
How many orders did each account place?

REWRITE:
1) Final Output: Multiple rows - account_id and count of orders.
2) Group/Scope: Group by account_id.
3) Selection Logic: Include all orders.
4) Final Calculation: COUNT of all orders per account.

LOGIC: Group orders by account_id. Then COUNT(*) for each account.*/

SELECT account_id,
       COUNT(*) AS num_orders
FROM orders
GROUP BY account_id;


/*QUESTION:
What is the total revenue by year?

REWRITE:
1) Final Output: Multiple rows - year and total revenue.
2) Group/Scope: Group by year.
3) Selection Logic: Include all orders.
4) Final Calculation: SUM of total_amt_usd per year.

LOGIC: Extract year from order date. Group orders by year. Then SUM(total_amt_usd) for each year.*/

SELECT DATE_PART('year', occurred_at) AS year,
       SUM(total_amt_usd) total_revenue_per_year
FROM orders
GROUP BY year
ORDER BY year;


/*QUESTION:
What is the total revenue by region?

REWRITE:
1) Final Output: Multiple rows - region name and total revenue.
2) Group/Scope: Group by region name.
3) Selection Logic: Include all orders and link them to regions.
4) Final Calculation: SUM of total_amt_usd per region.

LOGIC: Join orders to accounts. Join accounts to region. Group by region. SUM total_amt_usd for each region.*/

SELECT r.name AS region,
       SUM(o.total_amt_usd) AS total_revenue_per_region
FROM orders o
JOIN accounts a
ON o.account_id = a.id
JOIN sales_reps sr
ON sr.id = a.sales_rep_id
JOIN region r
ON r.id = sr.region_id
GROUP BY r.name;


/*QUESTION:
How many distinct channels exist in the web_events table?

REWRITE:
1) Final Output: One row - count of distinct channels.
2) Group/Scope: No grouping required.
3) Selection Logic: Include all rows from the web_events table.
4) Final Calculation: COUNT distinct values of channel.

LOGIC: Consider all rows. Identify unique channel values. Count how many unique channels exist.*/

SELECT COUNT(DISTINCT channel) distinct_channels
FROM web_events;


/*QUESTION:
Which accounts have placed more than 50 orders?

REWRITE:
1) Final Output: Multiple rows - account_id and number of orders.
2) Group/Scope: Group by account_id.
3) Selection Logic: Include only accounts that have more than 50 orders.
4) Final Calculation: COUNT orders per account.

LOGIC: Group orders by account_id. Count orders for each account. Keep only rows with count greater than 50.*/

SELECT account_id,
       COUNT(*) AS num_orders
FROM orders
GROUP BY account_id
HAVING COUNT(*) > 50;


/*QUESTION:
Which accounts have average order value greater than 3000 USD?

REWRITE:
1) Final Output: Multiple rows - account_id and average order value.
2) Group/Scope: Group by account_id.
3) Selection Logic: Keep only accounts whose average order value is more than 3000 USD.
4) Final Calculation: AVG(total_amt_usd) per account.

LOGIC: Group orders by account_id. AVG total_amt_usd for each account. Keep only rows with value greater than 3000 USD.*/

SELECT account_id,
       AVG(total_amt_usd) AS avg_order_value
FROM orders
GROUP BY account_id
HAVING AVG(total_amt_usd) > 3000;


/*QUESTION:
How many orders were placed in each month?

REWRITE:
1) Final Output: Multiple rows - year, month and count of orders.
2) Group/Scope: Group by year and month.
3) Selection Logic: Include all orders.
4) Final Calculation: COUNT orders per year and month.

LOGIC: Extract year and month from order date. Group orders by year and month. Count number of orders for each group.*/

SELECT DATE_PART('year', occurred_at) AS year,
       DATE_PART('month', occurred_at) AS month,
       COUNT(*) AS num_orders
FROM orders
GROUP BY year, month
ORDER BY year, month;


/*QUESTION:
What is the total revenue per year?

REWRITE:
1) Final Output: Multiple rows - year and total revenue.
2) Group/Scope: Group by year.
3) Selection Logic: Include all orders.
4) Final Calculation: SUM of total_amt_usd per year.

LOGIC: Extract year from order date. Group orders by year. SUM(total_amt_usd) for each year.*/

SELECT DATE_TRUNC('year', occurred_at) AS year,
       SUM(total_amt_usd) AS total_revenue
FROM orders
GROUP BY DATE_TRUNC('year', occurred_at)
ORDER BY year;